### PR TITLE
add an interface to new calculator (pwmat)

### PR DESCRIPTION
**Pull request by Liang-jianxin**
Add interface for new calculator (pwmat)
Description:
Added a new interface for the new calculator PWmat, implementing the functionality to read structure and force files.
Tested locally to ensure proper functionality.
Code structure has been standardized according to pre-commit.
Compatible with the main branch and does not introduce conflicts or disrupt existing functionality.

### CODE REVIEW

**Comment by atztogo** [comment]
Is this work in progress?

**Comment by atztogo** [comment]
@Liang-jianxin, please run pre-commit before your commit if you can. For the pre-commit, see https://github.com/phonopy/phonopy?tab=readme-ov-file#pre-commit.

**Comment by Liang-jianxin** [comment]
> @Liang-jianxin, please run pre-commit before your commit if you can. For the pre-commit, see https://github.com/phonopy/phonopy?tab=readme-ov-file#pre-commit.
okey, thanks for your suggestion, I will check it

**Comment by Liang-jianxin** [comment]
A new commit has been submitted after running pytest and pre-commit. 
It is worth noting that when running pre-commit there is an unusual output：
IndexError: list index out of range
Traceback (most recent call last):
  File "xxx/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "xxx/pre_commit_hooks/check_added_large_files.py", line 73, in main
    return find_large_added_files(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx/pre_commit_hooks/check_added_large_files.py", line 43, in find_large_added_files
    filter_lfs_files(filenames_filtered)
  File "xxx/pre_commit_hooks/check_added_large_files.py", line 28, in filter_lfs_files
    filename, filter_tag = stdout[i], stdout[i + 2]

after checking, the function is as follows：

def filter_lfs_files(filenames: set[str]) -> None:  # pragma: no cover (lfs)
    """Remove files tracked by git-lfs from the set."""
    if not filenames:
        return

    check_attr = subprocess.run(
        ('git', 'check-attr', 'filter', '-z', '--stdin'),
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        encoding='utf-8',
        check=True,
        input='\0'.join(filenames),
    )
    stdout = zsplit(check_attr.stdout)
    print(stdout) as follows：

['test/phonopy_params_Si.yaml: filter: unspecified\nscripts/phonopy-load: filter: unspecified\ntest/structure/tio2_qpoints.yaml: filter: unspecified\ndoc/SnO2-GZG-offset.png: filter: unspecified\ntest/FORCE_SETS_TiO2: filter: unspecified\nexample/Si-nosym/mesh.conf: filter: unspecified\ntest/phonon/POSCAR_P31m: filter: unspecified\ntest/interface/test_abacus.py: filter: unspecified\nexample/Si-CP2K/README.md: filter: unspecified\nphonopy/phonon/__init__.py: filter: unspecified\nexample/NaCl-QE-q2r/NaCl.ph.in: filter: unspecified\nexample/TiO2-anatase/band.conf: filter: unspecified\nexample/Si-TURBOMOLE/example-001/energy: filter: unspecified\ndoc/NaCl-VASPdfpt.png: filter: unspecified\nc/phonopy.c: filter: unspecified\nphonopy/interface/phonopy_yaml.py: filter: unspecified\nphonopy/interface/abacus.py: filter: unspecified\ndoc/procedure.png: filter: unspecified\nexample/Si-TURBOMOLE/example-001/supercell-001.out: filter: unspecified\nexample/Si-QHA/thermal_properties.yaml--3: filter: unspecified\nexample/Al-ABACUS/abacus-lcao/disp-001/STRU-001: filter: unspecified\nphonopy/spectrum/dynamic_structure_factor.py: filter: unspecified\ndoc/NaCl-band.png: filter: unspecified\nexample/Al-QHA/thermal_properties.yaml--4: filter: unspecified\nphonopy/phonon/moment.py: filter: unspecified\nphonopy/harmonic/dynamical_matrix.py: filter: unspecified\ndoc/rotation-C4.png: filter: unspecified\n']
please check function zsplit( ) and modify it

**Comment by atztogo** [comment]
Probably your issue on pre-commit run is due to your environment.

@Liang-jianxin, could you write the aim of your PR on top of this PR, where it is "No description provided."

**Comment by Liang-jianxin** [comment]
Already added the PR description, but still have Some checks were not successful, do I need to make any changes?

**Comment by atztogo** [comment]
If you want to add documentation like https://github.com/phonopy/phonopy/blob/develop/doc/qe.md, I will wait for merging. Otherwise I will merge it now. For calculators, if we get questions, we will probably forward to you, so it may be convenient if your contact address is presented, but it is not mandatory.

**Comment by Liang-jianxin** [comment]
> If you want to add documentation like https://github.com/phonopy/phonopy/blob/develop/doc/qe.md, I will wait for merging. Otherwise I will merge it now. For calculators, if we get questions, we will probably forward to you, so it may be convenient if your contact address is presented, but it is not mandatory.

thanks, you can merge immediately. If any questions, please contact me through the GitHub email.

**Comment by atztogo** [comment]
From next time, it would be helpful if you PR from your topic branch of your fork.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Pull request merged**
