### PR TITLE
Implementation of the the Wigner thermal conductivity formula

### PR DESCRIPTION
**Pull request by MSimoncelli**
Implementation of the the Wigner thermal conductivity formula (both with the exact and RTA scattering operator) described in [Simoncelli, Marzari, Mauri, Nature Physics, 15 (8), 809 (2019); Simoncelli, Marzari, Mauri arXiv:2112.06897 (2021)].

### CODE REVIEW

**Comment by atztogo** [comment]
Thanks @MSimoncelli. Could you write tests for velocity_operator.py? If you have no idea about the test, please let me know.
I think showing Total execution time is unnecessary.

**Comment by MSimoncelli** [comment]
Thanks for the prompt feedback @atztogo. I haven't written test for velocity_operator.py because I do not know what they are. Could you let me know more about this? I am also available for a zoom call if needed. 
I printed the total execution time because I find it very useful in phono3py, since in complex crystals calculations can be quite long. Anyway, if you prefer I can remove the total time.

**Comment by atztogo** [comment]
@MSimoncelli, I started merging this PR into phono3py. See https://github.com/phonopy/phono3py/pull/83. I started with merging velocity operator before thermal conductivity.

Your tests of velocity operator seem system dependent, and fail in the github workflow (https://github.com/phonopy/phono3py/runs/5431823650?check_suite_focus=true), and also on my mac. Do you want to fix code or relax the tolerance?

**Comment by MSimoncelli** [comment]
@atztogo I have updated the code, now the test for the velocity operator works on the GitHub workflow

**Comment by atztogo** [comment]
This has been done manually.

**Pull request closed without merging**
