### PR TITLE
Refinement of the Fleur interface

### PR DESCRIPTION
**Pull request by neukirchen-212**
Hello once more!

I did some refinement on the interface for the Fleur code I committed recently. For now the work is finished and I will talk to our resident Aiida experts on how to implement an Aiida-phonopy plugin for Fleur in the foreseeable future. Until then this is all that needs to be done.

I will then also write a small sanity check for Fleur-phonopy calculations akin to the one for the TURBOMOLE implementation and a tutorial on how to use Fleur and Phonopy in conjunction on our website, which I will then link.

Stay healthy!

Best, Alex

### CODE REVIEW

**Comment by atztogo** [comment]
Thanks @neukirchen-212. Do you think this is ready to release?

**Comment by neukirchen-212** [comment]
I'm quite confident it is @atztogo . If there are problems with it they will emerge over time when people use it and be brought to my attention when they complain. 

Most error sources stem from the correct usage of Fleur to prepare forces for phonopy and those errors I will try to suppress by writing a detailed tutorial on our homepage. :)

Thanks for your support!

**Comment by atztogo** [comment]
@neukirchen-212, maybe have you forgotten to git-add `command-options.rst`? The following is sphinx warning that I have encountered:
```
Fleur.rst:35: WARNING: undefined label: fleur_mode (if the link has no caption the label must precede a section header)
Fleur.rst:60: WARNING: undefined label: fleur_force_sets_option (if the link has no caption the label must precede a section header)
```

**Comment by neukirchen-212** [comment]
Not that, but I forgot to add the respective sections to the file. Just a second.

**Pull request merged**
