### PR TITLE
Reset warnings for issue #380

### PR DESCRIPTION
**Pull request by atztogo**
Reset warnings for fixing issue #380.

### CODE REVIEW

**Comment by JaGeo** [comment]
I've been thinking if the second solution in this answer - using the context module - might be more appropriate as we would otherwise again reset all warning configurations for all vode afterwards. The solution in your PR works in my use case but I am not sure if it works for all potential use cases:
https://stackoverflow.com/a/9134842

I will test the solution mentioned there now.

**Comment by JaGeo** [comment]
So for me, using `with warnings.catch_warnings():` befor changing the warnings filter and move the code afterwards into a block works as well. I think this would be a better solution as it will not change the warning settings users might have set before or afterwards.

**Comment by atztogo** [comment]
Good suggestion. How about 214ba7a?

**Comment by JaGeo** [comment]
This looks great! I would be happy if this could be merged! Thank you so much!

**Pull request merged**
