### PR TITLE
Castep interface support added

### PR DESCRIPTION
**Pull request by ladyteam**
Please consider to include CASTEP support into the master branch.

Warm wishes,
Eugene Roginskii

### CODE REVIEW

**Comment by atztogo** [comment]
Thanks. Merged. You can also add test if you want. The location is here, `phonopy/test/interface/`. The tests run every push to github on traivs-CI.

**Comment by ladyteam** [comment]
Thank you. I will try to add test later, need some time to understand how test works.

The discription of CASTEP input file is very close to VASP POSCAR. The input file consist from blocks. The lattice vectors are discribed in block LATTICE_CART, for example:
%BLOCK LATTICE_CART
     3.1839690996991283    0.0000000000000000    0.0000000000000000
    -1.5919845498495642    2.7573981252041131    0.0000000000000000
     0.0000000000000000    0.0000000000000000    5.1672490853859836
%ENDBLOCK LATTICE_CART
Atomic positions are given in block POSITIONS_FRAC, for example:
%BLOCK POSITIONS_FRAC
Ga  0.3333333333333333  0.6666666666666666  0.0000000000000000 spin=3.0
Ga  0.6666666666666667  0.3333333333333333  0.5000000000000000 spin=3.0
N   0.3333333333333333  0.6666666666666666  0.3751000000000000
N   0.6666666666666667  0.3333333333333333  0.8751000000000000 
%ENDBLOCK POSITIONS_FRAC
As you see each position accompined by atomic label. 
In case of spin polarized calculations the variable "spin" is added. The spin polarization is skipped in the patch, bacause I need to understan the way how to set up spins. As I understood this could be made by calling cell.set_magnetic_moments() function. Will try to implement spin polarization functionality and then com back to tests.

**Comment by atztogo** [comment]
That's nice. Your can use attributes `magnetic_moments`,
```python
In [1]: from phonopy.interface.calculator import read_crystal_structure
In [2]: cell, _ = read_crystal_structure("POSCAR-unitcell", interface_mode='vasp')
In [3]: len(cell)
Out[3]: 8
In [4]: cell.magnetic_moments = [1, 1, 1, 1, -1, -1, -1, -1]
In [4]: cell.magnetic_moments
Out[4]: array([ 1.,  1.,  1.,  1., -1., -1., -1., -1.])
```

**Comment by atztogo** [comment]
@ladyteam , probably documentation will be needed. Could you write it?

**Comment by ladyteam** [comment]
Dear Dr. Togo, I don't think there is something specific about castep interface, so I don't even know what kind of documentation could be provided. But what is really needed is expamples, like NaCl-CRYSTAL in example directory. I have made tests for NaCl and Cr crystals, but I dont know how to upload these examples. Should I add examples to my copy of development branch and then make new pull requiest?

**Comment by atztogo** [comment]
Yes, exactly. Thanks. I will write documentation, which will be almost just the copy of README (if available) in your example.

**Pull request merged**
