### PR TITLE
Compatible with higher ABACUS versions

### PR DESCRIPTION
**Pull request by 1041176461**
Version 3.4.0 of ABACUS has done some formatting on the output file. This PR is for synchronized updates.

### CODE REVIEW

**Comment by atztogo** [comment]
@1041176461, do you want to write test for this change?

It is probably more convenient for you to make a specific branch in your fork for making PR [(github doc)](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork), and before your git commit, I would like you to run pre-commit, see https://github.com/phonopy/phonopy?tab=readme-ov-file#pre-commit.

**Comment by 1041176461** [comment]
Thanks! I added test for changes, and I will follow your advice next time.

**Comment by atztogo** [comment]
@1041176461, your test failed, although it might work on your environment at your current directory that you ran the test.

Please refer the following line to specify the file name:
https://github.com/phonopy/phonopy/blob/fe81eb325e75c48ac8dcc68c85e5212f39307f5c/test/interface/test_vasp.py#L22

As you can see above, pre-commit.ci fixed again your commit. You might run pre-commit this time, but unless so, please use pre-commit if you can next time.

**Comment by 1041176461** [comment]
Ok, I think I should close this PR, and resubmit it based on your steps

**Pull request closed without merging**
