### PR TITLE
fix for  "--gnuplot should not require --legacy"

### PR DESCRIPTION
**Pull request by kgmat**
Dear Dr. Togo,

  This PR is about fixing of "--gnulot should not require --legacy"

  Thanks & Regards

### CODE REVIEW

**Comment by atztogo** [comment]
Thanks, @kgmat. Now there are two gnuplot output routines, one in `def plot` and the other in `def old_plot`. Do you think they can be merged to one?

**Comment by kgmat** [comment]
@atztogo, I was actually thinking of that but ended with keeping them in both the functions. I will try to keep it in one place. Thanks

**Comment by atztogo** [comment]
@kgmat , thanks for your consideration. I understand `phonopy-bandplot` is so messy, fragile, and there is no test. It's my fault. So please modify as you like. You can break it and of course, it is no need to be perfect at all.

**Comment by kgmat** [comment]
Dear Dr. Togo, as you suggested. Now a separate function is there in `phonopy-bandplot` for writing gnuplot-style output. 

Thanks

**Comment by atztogo** [comment]
Great. Merged. Thanks.

**Pull request merged**
