### PR TITLE
Fleur interface for phonopy

### PR DESCRIPTION
**Pull request by neukirchen-212**
Hello to all phonopy maintainers!

I am trying to implement an interface to phonopy for the all-electron FLAPW DFT code Fleur developed at the Forschungszentrum Jülich. As is, when I operate it for an input file with a simple cubic Bravais matrix it works well and I can produce a phonon bandstructure akin to the one produced e.g. by the Elk example. However, before the interface goes into the main code you should of course have a say in reviewing it and before even that, I have some questions regarding my implementation.

1) If I set up the example system I provided with an fcc Bravais matrix and one atom instead of the simple cubic one with a 4 atom basis, the final step of creating the dispersion from the FORCE_SETS fails. Tracing the issue back through the code i get the following output and stacktrace (with some additional prints I have put in to supervise the matrices):

$ phonopy --fleur -c fleur_inpgen -p --dim="2 2 2" --pa="0 1/2 1/2 1/2 0 1/2 1/2 1/2 0" --band="1/2 1/2 1/2 0 0 0 1/2 0 1/2"
        _
  _ __ | |__   ___  _ __   ___   _ __  _   _
 | '_ \| '_ \ / _ \| '_ \ / _ \ | '_ \| | | |
 | |_) | | | | (_) | | | | (_) || |_) | |_| |
 | .__/|_| |_|\___/|_| |_|\___(_) .__/ \__, |
 |_|                            |_|    |___/
                                       2.8.1

Python version 3.8.5
Spglib version 1.16.0

{'unitcell': <phonopy.structure.atoms.PhonopyAtoms object at 0x7f4895c54250>, 'supercell_matrix': array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 2]]), 'primitive_matrix': array([[0. , 0.5, 0.5],
       [0.5, 0. , 0.5],
       [0.5, 0.5, 0. ]]), 'optional_structure_info': ('fleur_inpgen', ['13.1'], ['Aluminium test Fleur', '\n', '&atom element="al" id=13.1 rmt=2.50 lmax=12 lnonsph=12 /\n', "&exco xctyp='vwn' /\n", '&comp kmax=4.0 gmax=24.01 gmaxxc=24.01 /\n', '&kpt div1=4 div2=4 div3=4 /\n', '&end /\n']), 'interface_mode': 'fleur', 'phonopy_yaml': None, 'magmoms': None}

Unitcell:
lattice:
- [     0.000000000000000,     3.828000000000000,     3.828000000000000 ] # a
- [     3.828000000000000,     0.000000000000000,     3.828000000000000 ] # b
- [     3.828000000000000,     3.828000000000000,     0.000000000000000 ] # c
points:
- symbol: Al # 1
  coordinates: [  0.000000000000000,  0.000000000000000,  0.000000000000000 ]
  mass: 26.981539

Supercell:
lattice:
- [     0.000000000000000,     7.656000000000000,     7.656000000000000 ] # a
- [     7.656000000000000,     0.000000000000000,     7.656000000000000 ] # b
- [     7.656000000000000,     7.656000000000000,     0.000000000000000 ] # c
points:
- symbol: Al # 1
  coordinates: [  0.000000000000000,  0.000000000000000,  0.000000000000000 ]
  mass: 26.981539
- symbol: Al # 2
  coordinates: [  0.500000000000000,  0.000000000000000,  0.000000000000000 ]
  mass: 26.981539
- symbol: Al # 3
  coordinates: [  0.000000000000000,  0.500000000000000,  0.000000000000000 ]
  mass: 26.981539
- symbol: Al # 4
  coordinates: [  0.500000000000000,  0.500000000000000,  0.000000000000000 ]
  mass: 26.981539
- symbol: Al # 5
  coordinates: [  0.000000000000000,  0.000000000000000,  0.500000000000000 ]
  mass: 26.981539
- symbol: Al # 6
  coordinates: [  0.500000000000000,  0.000000000000000,  0.500000000000000 ]
  mass: 26.981539
- symbol: Al # 7
  coordinates: [  0.000000000000000,  0.500000000000000,  0.500000000000000 ]
  mass: 26.981539
- symbol: Al # 8
  coordinates: [  0.500000000000000,  0.500000000000000,  0.500000000000000 ]
  mass: 26.981539

Supercell matrix:
[[2 0 0]
 [0 2 0]
 [0 0 2]]

Primitive matrix:
[[0.  0.5 0.5]
 [0.5 0.  0.5]
 [0.5 0.5 0. ]]

Transformation matrix/"Primitive frame":
[[0.   0.25 0.25]
 [0.25 0.   0.25]
 [0.25 0.25 0.  ]]

Traceback (most recent call last):
  File "/home/alex/anaconda3/bin/phonopy", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/alex/phonopy/scripts/phonopy", line 43, in <module>
    main(**argparse_control)
  File "/home/alex/phonopy/phonopy/cui/phonopy_script.py", line 1589, in main
    phonon = init_phonopy(settings, cell_info, symprec, log_level)
  File "/home/alex/phonopy/phonopy/cui/phonopy_script.py", line 1486, in init_phonopy
    phonon = Phonopy(
  File "/home/alex/phonopy/phonopy/api_phonopy.py", line 132, in __init__
    self._build_primitive_cell()
  File "/home/alex/phonopy/phonopy/api_phonopy.py", line 3124, in _build_primitive_cell
    self._primitive = get_primitive(
  File "/home/alex/phonopy/phonopy/structure/cells.py", line 55, in get_primitive
    return Primitive(supercell,
  File "/home/alex/phonopy/phonopy/structure/cells.py", line 390, in __init__
    self._run(supercell, positions_to_reorder=positions_to_reorder)
  File "/home/alex/phonopy/phonopy/structure/cells.py", line 431, in _run
    self._p2s_map = self._create_primitive_cell(
  File "/home/alex/phonopy/phonopy/structure/cells.py", line 440, in _create_primitive_cell
    trimmed_cell, p2s_map, _ = _trim_cell(
  File "/home/alex/phonopy/phonopy/structure/cells.py", line 671, in _trim_cell
    tcell = TrimmedCell(relative_axes,
  File "/home/alex/phonopy/phonopy/structure/cells.py", line 535, in __init__
    self._run(cell, relative_axes, positions_to_reorder, symprec)
  File "/home/alex/phonopy/phonopy/structure/cells.py", line 589, in _run
    raise RuntimeError("Remapping of atoms by TrimmedCell failed.")
RuntimeError: Remapping of atoms by TrimmedCell failed.

A certain check considering the mapping to the primitive cell fails so it appears one of the matrices from which it is built appears to be faulty in my interface. However I do not see yet where it went wrong. Maybe one of you has an idea on this. Going for an equivalent setup for an Elk conversion yielded the same problem by the way, so  it might also be a more general problem or a mistake in the setup I make.

2) The non-analytic term correction is something I did not work with as of yet. Is this feature something I need to provide additional Fleur output for or is it calculated inside the phonopy code? This determines, whether I refer to it in my interface.

3) I saw that some interfaces come with a quick sanity check for e.g. their conversion. Should I write such a check as well or is it rather unimportant?

4) Is there anything else that appears fishy to you at first glance and should be thought about some more?

Best regards and a happy new year,

M.Sc. Alexander Neukirchen

### CODE REVIEW

**Comment by atztogo** [comment]
Merged. Thanks.

Your unit cell is already the primitive cell. So your `primitive_matrix` is the unit matrix, i.e., you don't need to specify `--pa` or `--pa=P`. If you wonder, you can try `--pa=auto` to see the phonopy's suggestion from the crystallographic sense.

**Comment by neukirchen-212** [comment]
I see - thanks! I already suspected it was due to my faulty usage.

Then I can move on to the two remaining points I wonder about:

The non-analytic term correction is something I did not work with as of yet. Is this feature something I need to provide additional Fleur output for or is it calculated inside the phonopy code nevermind the choice of calculator? This determines, whether I refer to it in my interface.

I saw that some interfaces come with a quick sanity check for e.g. their conversion. Should I write such a check as well or is it rather unimportant?

**Comment by atztogo** [comment]
At this moment, you can provide the features as you need and at your convenience. You can update the Fleur interface whenever you want via PR. If we get questions or requests on this interface, we will ask you to respond them. A request from phonopy is that the code license of the interface follows the 3-Clause BSD License (I assume you follow it.) From the point of view of software license, what is impossible is to call other library that is under incompatible licenses such as GPL.

**Comment by neukirchen-212** [comment]
Ok. Considering the licensing:

For the new files I wrote, I put the license into the interface file the same way other codes do. So that should be just fine.

The Fleur code operates under the MIT license (https://choosealicense.com/licenses/mit/) which is quite similar to BSD-3, except for the point that you specify the need to ask for your permission to "endorse or promote" your code (as far as I undersatnd it here: https://choosealicense.com/licenses/bsd-3-clause-clear/).

I would like to make sure it is ok to refer to our code and website within your documentation and refer to phonopy from our website E.g. "Fleur can be used to produce phonon spectra etc. with phonopy [https://phonopy.github.io/phonopy/; 
“First principles phonon calculations in materials science”,

Atsushi Togo and Isao Tanaka, Scr. Mater., 108, 1-5 (2015)

http://dx.doi.org/10.1016/j.scriptamat.2015.07.021 (Open access)] when using the develop branch. For instructions on how to use it refer to the documentation file inside the source code." Or is there something else I need to consider?

**Comment by atztogo** [comment]
Thanks for your introduction of Fleur code license. I didn't know it is under MIT. Nice.

What I am mainly afraid of is GPL. In my current policy, just one line of `import some_gpl_code` is not allowed in the distributed phonopy code even if it is not actually imported. But I prefer to avoid importing external libraries except for very essential ones.

> I would like to make sure it is ok to refer to our code and website within your documentation and refer to phonopy from our website E.g.

No problem and thanks for taking care of it.

> Or is there something else I need to consider?

Already very good, but I appreciate if you consider:
* Tests are welcome (https://github.com/phonopy/phonopy/tree/develop/test/interface.) Pytest is preferable.
* You may put your name in fleur.py instead of my name if you like.

For these, PR is welcome at anytime.
Please let me know if you want me to release (i.e., merging to master and deploying packages) including your interface.

**Pull request merged**
