### PR TITLE
Fix: find pseudo from STRU file of abacus

### PR DESCRIPTION
**Pull request by hongriTianqi**
Dear Prof. Togo,

I open this pull request to treat the bug in finding pseudo file from the `STRU` file in the ABACUS interface. The reasons: the header of `STRU` can both be
```
ATOMIC_SPECIES
Mo 95.94 Mo_ONCV_PBE-1.0.upf
S 32.065 S_ONCV_PBE-1.0.upf
```
or
```
ATOMIC_SPECIES
Mo 95.94 Mo_ONCV_PBE-1.0.upf upf201
S 32.065 S_ONCV_PBE-1.0.upf upf201
```
For the latter case, the code will cause error. 

This PR is opened to fix this error. 

Thanks for your help.
Best,
Tianqi Zhao

### CODE REVIEW

**Comment by atztogo** [comment]
I have no idea about abacus. Could @1041176461 have a look at it?

@hongriTianqi, could you solve a [pre-commit issue](https://results.pre-commit.ci/run/github/7108011/1676000377.DwhV5V61TMmJ28ryI5XPUw)? About pre-commit, you may find some information at https://github.com/phonopy/phonopy#development. In case you have no idea about it, please let me know.

**Comment by hongriTianqi** [comment]
> I have no idea about abacus. Could @1041176461 have a look at it?
> 
> @hongriTianqi, could you solve a [pre-commit issue](https://results.pre-commit.ci/run/github/7108011/1676000377.DwhV5V61TMmJ28ryI5XPUw)? About pre-commit, you may find some information at https://github.com/phonopy/phonopy#development. In case you have no idea about it, please let me know.

Dear Prof. Togo,

I have communicated with @1041176461 (Dr. Yuyang Ji). He agrees with this modification of the abacus interface code. The pre-commit issue shows problems with annotations in the file `phonopy/structure/cells.py`, as
```
phonopy/structure/cells.py:1375 in public function `compute_permutation_for_rotation`:
        D202: No blank lines allowed after function docstring (found 1)
```

However, I did nothing on the above file. It should not be caused by my PR, i.e. only a minor modification of the file "phonopy/interface/abacus.py". Could you please help with this pre-commit error? Thanks!

Best

**Comment by 1041176461** [comment]
> I have no idea about abacus. Could @1041176461 have a look at it?
> 
> @hongriTianqi, could you solve a [pre-commit issue](https://results.pre-commit.ci/run/github/7108011/1676000377.DwhV5V61TMmJ28ryI5XPUw)? About pre-commit, you may find some information at https://github.com/phonopy/phonopy#development. In case you have no idea about it, please let me know.

I guess this error comes from commit 1a891f9e9d2abf6e358e1e363376d8d07e380774
image
We may need to delete the blank line at line 1407 which is not allowed by pre-commit.ci.

**Comment by hongriTianqi** [comment]
> > I have no idea about abacus. Could @1041176461 have a look at it?
> > @hongriTianqi, could you solve a [pre-commit issue](https://results.pre-commit.ci/run/github/7108011/1676000377.DwhV5V61TMmJ28ryI5XPUw)? About pre-commit, you may find some information at https://github.com/phonopy/phonopy#development. In case you have no idea about it, please let me know.
> 
> I guess this error comes from commit [1a891f9](https://github.com/phonopy/phonopy/commit/1a891f9e9d2abf6e358e1e363376d8d07e380774) image We may need to delete the blank line at line 1407 which is not allowed by pre-commit.ci.

Thanks for @1041176461 's suggestion! I have tried to remove the blank line at 1407. However, the pre-commit hook added it back again. So the pre-commit is making errors by itself :-(. This will be solved if I move the second block of annotations below the def of a inner function. Would you @atztogo agree with this?

**Comment by atztogo** [comment]
I see. Sorry for taking your time for the pre-commit issue of `phonopy/structure/cells.py`, which would have to be taken care of me. This issue didn't happen until now, so I guess it is due to some update of the pre-commit service side.

Many thanks @hongriTianqi for your commit and @1041176461 for your review.

**Comment by hongriTianqi** [comment]
> I see. Sorry for taking your time for the pre-commit issue of `phonopy/structure/cells.py`, which would have to be taken care of me. This issue didn't happen until now, so I guess it is due to some update of the pre-commit service side.
> 
> Many thanks @hongriTianqi for your commit and @1041176461 for your review.

Thanks!

**Pull request merged**
